export default {
  schedule: false,
  scheduleLegacy: false,
  sponsors: false,
  association: false,
  jobs: false,
  talks: false,
  speakers: false,
  live: false,
  faq: false,
  codeOfConduct: false,
  legalNotice: false,
  wip: true,
  ticketing: false,
};
