export default {
  schedule: true,
  scheduleLegacy: false,
  sponsors: true,
  association: true,
  jobs: true,
  talks: false,
  speakers: false,
  live: false,
  faq: true,
  codeOfConduct: true,
  legalNotice: true,
  wip: false,
  ticketing: true,
};
