runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: ''
  DATABASE_USER: ''
  DATABASE_PASSWORD: ''
  INSTANCE_CONNECTION_NAME: ''

beta_settings:
  cloud_sql_instances: ''